### ISSUE TITLE
Create Error component

### ISSUE THREAD

**Issue by natdudley-EDA** [harakeke-2020/Final-Project-Be-Seasonable#11]
Similar to the wait component.

This Error component should display its message prop to the user if it's not null. The prop should ultimately come from the Redux store's error property, therefore it should be a connected component.

Tasks:

- [x]  Create an Error component that displays an error to the user
- [x]  Test the component shows and doesn't show the message based on its prop

**Comment by brendan-olphert** [comment]
Docs updated.
commit: 2f6ee20
