### ISSUE TITLE
Research ethical issues for each food type

### ISSUE THREAD

**Issue by natdudley-EDA** [harakeke-2020/Final-Project-Be-Seasonable#44]
For each food type, check for issues including:

- grown overseas year round (carbon cost)
- labour issues
- water use/other environmental issues in NZ

Collect links to news or research.
Write a summary paragraph explaining key takeaways.

Fruits:
- [x] Apple
- [x] Avo
- [x] Banana
- [x] Beans
- [x] Broccoli
- [x] Cabbage
- [x] Capsicum
- [x] Carrots
- [x] Cauli
- [x] Celery
- [x] Courgette
- [x] Cucumber
- [x] Grapes
- [x] Kiwifruit
- [x] Kumara
- [x] Lettuce
- [x] Mandarins
- [x] Mushrooms
- [x] Onions
- [x] Oranges
- [x] Parsnips
- [x] Pears
- [x] Pineapple
- [x] Potatoes
- [x] Pumpkin
- [x] Tomatoes

- [x] Add to food table in seed.

**Comment by lorenzo-joseph-fernandez-19** [comment]
Labour issues for kiwifruit - https://www.nzherald.co.nz/nz/news/article.cfm?c_id=1&objectid=12256559

**Comment by brendan-olphert** [comment]
added in commits: 41bbf5c
