### ISSUE TITLE
foodDetails GET route

### ISSUE THREAD

**Issue by lorenzo-joseph-fernandez-19** [harakeke-2020/Final-Project-Be-Seasonable#50]
a backend route that is called by an api. 

- [x] The api is at /api/v1/foods/:month/:id
- [x] The id would relate to a food id. 
- [x] When the GET route is called, it calls the database call 'getFoodDetails(month, id)'.
- [x] The month will be req.params.month, and is expected to be a number.
- [x] get back an object containing and array of foods, and to pass this to the route as JSON.
- [x] The route should provide an error message if the database call fails saying "We had a problem getting food details. You can try refreshing the page"
- [x] write tests
- [x] write docs

**Comment by brendan-olphert** [comment]
added in commit
75a604b
