### ISSUE TITLE
Redux store set up for Food Details

### ISSUE THREAD

**Issue by natdudley-EDA** [harakeke-2020/Final-Project-Be-Seasonable#64]
An API has been made for the FoodDetails, but we need to add a reducer and action in the store to handle getting and storing the food detail for the current active food.

- [x] Test getFoodDetailsReducer.js
- [x] Test getFoodDetailsActions.js
- [x] Connect FoodDetail.jsx connected to redux store

**Comment by lorenzo-joseph-fernandez-19** [comment]
- [ ] Actions
- [ ] Reducers
- [ ] Tests
- [ ] Docs

Commit: 0bbabac
