### ISSUE TITLE
Create client side route for /food/:id

### ISSUE THREAD

**Issue by natdudley-EDA** [harakeke-2020/Final-Project-Be-Seasonable#8]
Once we're ready for food details, there needs to be a client side route that connects to the FoodDetail component.

**Comment by lorenzo-joseph-fernandez-19** [comment]
Commit: b9caa9e
Docs still need to be written. Will write these once we know the data structure returned from db.

**Comment by lorenzo-joseph-fernandez-19** [comment]
Docs written for this issue.
