### ISSUE TITLE
Wait indicator component

### ISSUE THREAD

**Issue by natdudley-EDA** [harakeke-2020/Final-Project-Be-Seasonable#9]
Create a WaitIndicator component that displays a CSS animation when its busy prop is true. When false the component should not show the animation. The busy prop should ultimate come from the Redux store.

Tasks:

- [x]  Create connected component
- [x]  Create reducer for a pending property
- [x]  Create an async action creator for retrieving food details
- [x]  Test the component UI for both busy and not busy conditions (snapshot testing is fine)
- [x]  Test the reducer and action creator
- [x]  Write appropriate docs

**Comment by H-THO** [comment]
All Done - Thanks for the code review y'all 🌶️
